on:
  release:
    types:
      - published

name: Push to Godot Asset Library

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Push new release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Push to Godot Asset Library
        uses: wjt/godot-asset-lib-action@fd3395aa70bba333c0d3cc33c78dc03c18d149ae
        with:
          username: ${{ secrets.GODOT_ASSET_LIBRARY_USERNAME }}
          password: ${{ secrets.GODOT_ASSET_LIBRARY_PASSWORD }}
          assetId: 3095
          assetTemplate: asset-template.json.hb
